const fs = require("fs");
const path = require("path");
const { GoogleGenAI } = require("@google/genai");

const meta = {
  name: "googleart",
  version: "1.0.0",
  description: "Generates AI art using Google's Imagen model (via @google/genai)",
  author: "Ry",
  method: "get",
  category: "image generation",
  path: "/googleart?prompt=",
};

// Add your API key here if you’re not using environment variables
// Example: const apikey = "YOUR_GOOGLE_API_KEY_HERE";
const apikey = process.env.GOOGLE_API_KEY || "AIzaSyBAG9ad84ZWCDSAjey346zCgXLTjMLr3aE";

async function onStart({ req, res }) {
  try {
    const prompt = req.query.prompt;
    if (!prompt) {
      return res.status(400).json({ error: "Prompt parameter is required" });
    }

    // Initialize GoogleGenAI client
    const ai = new GoogleGenAI({
      apiKey: apikey,
    });

    // Generate images using Imagen model
    const response = await ai.models.generateImages({
      model: "gemini-2.5-flash-image",
      prompt: prompt,
      config: {
        numberOfImages: 1, // You can increase this if needed
      },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      return res.status(500).json({ error: "No images generated by Google GenAI" });
    }

    // Convert Base64 to buffer
    const imgBytes = response.generatedImages[0].image.imageBytes;
    const imageBuffer = Buffer.from(imgBytes, "base64");

    // Optional: save image locally
    const outputPath = path.join(__dirname, `generated-${Date.now()}.png`);
    fs.writeFileSync(outputPath, imageBuffer);

    // Send image as response
    res.setHeader("Content-Type", "image/png");
    res.send(imageBuffer);
  } catch (error) {
    console.error("Google Imagen generation error:", error);
    res.status(500).json({ error: "Failed to generate image from Google GenAI" });
  }
}

module.exports = { meta, onStart };